# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-19 06:40
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_phone', '0013_auto_20180301_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructions',
            name='language',
            field=models.CharField(blank=True, choices=[(b'en', 'English')], default='', max_length=8, validators=[django.core.validators.RegexValidator('^(|en)$')]),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='language',
            field=models.CharField(blank=True, choices=[(b'en', 'English')], default='', max_length=8, validators=[django.core.validators.RegexValidator('^(|en)$')]),
        ),
    ]
