# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-16 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcari', '0071_auto_20180214_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondent',
            name='PS',
            field=models.CharField(blank=True, choices=[('', '(Empty)'), ('4PS', '4PS'), ('MCCT', 'MCCT'), ('GIDA', 'GIDA')], default='', max_length=64),
        ),
        migrations.AddField(
            model_name='respondent',
            name='address',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='respondent',
            name='contact',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='respondent',
            name='group',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='respondent',
            name='name',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='respondent',
            name='organization',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
