# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-17 09:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcari', '0073_auto_20180417_0134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respondent',
            old_name='PPI_I',
            new_name='PPiI',
        ),
        migrations.RenameField(
            model_name='respondent',
            old_name='PPI_II',
            new_name='PPiII',
        ),
        migrations.RenameField(
            model_name='respondent',
            old_name='PPI_III',
            new_name='PPiIII',
        ),
        migrations.RenameField(
            model_name='respondent',
            old_name='PPI_IV',
            new_name='PPiIV',
        ),
        migrations.RenameField(
            model_name='respondent',
            old_name='PPI_IX',
            new_name='PPiIX',
        ),
        migrations.RenameField(
            model_name='respondent',
            old_name='PPI_V',
            new_name='PPiV',
        ),
        migrations.RenameField(
            model_name='respondent',
            old_name='PPI_VI',
            new_name='PPiVI',
        ),
        migrations.RenameField(
            model_name='respondent',
            old_name='PPI_VII',
            new_name='PPiVII',
        ),
        migrations.RenameField(
            model_name='respondent',
            old_name='PPI_VIII',
            new_name='PPiVIII',
        ),
        migrations.RenameField(
            model_name='respondent',
            old_name='PPI_X',
            new_name='PPiX',
        ),
    ]
