# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-19 11:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcari', '0075_auto_20180418_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respondent',
            name='PPiIIIQI',
            field=models.CharField(blank=True, choices=[('', '(Empty)'), ('Di 5-18', 'Di 5-18'), ('Kehnaba', 'Kehnaba'), ('Oway', 'Oway')], default='', max_length=64, validators=[django.core.validators.RegexValidator('^(|M|F)$')]),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='PPiIIIQII',
            field=models.CharField(blank=True, choices=[('', '(Empty)'), ('Di 5 o subra', 'Di 5 o subra'), ('Di', 'Di'), ('Oway', 'Oway')], default='', max_length=64, validators=[django.core.validators.RegexValidator('^(|M|F)$')]),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='PPiIIIQIII',
            field=models.CharField(blank=True, choices=[('', '(Empty)'), ('Da galbek', 'Da galbek'), ('Oway', 'Oway'), ('Di', 'Di')], default='', max_length=64, validators=[django.core.validators.RegexValidator('^(|M|F)$')]),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='PPiIIQI',
            field=models.CharField(blank=True, choices=[('', '(Empty)'), ('Di 5-18', 'Di 5-18'), ('Kehnaba', 'Kehnaba'), ('Oway', 'Oway')], default='', max_length=64, validators=[django.core.validators.RegexValidator('^(|M|F)$')]),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='PPiIIQII',
            field=models.CharField(blank=True, choices=[('', '(Empty)'), ('Di 5 o subra', 'Di 5 o subra'), ('Di', 'Di'), ('Oway', 'Oway')], default='', max_length=64, validators=[django.core.validators.RegexValidator('^(|M|F)$')]),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='PPiIIQIII',
            field=models.CharField(blank=True, choices=[('', '(Empty)'), ('Da galbek', 'Da galbek'), ('Oway', 'Oway'), ('Di', 'Di')], default='', max_length=64, validators=[django.core.validators.RegexValidator('^(|M|F)$')]),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='PPiIQI',
            field=models.CharField(blank=True, choices=[('', '(Empty)'), ('Di 5-18', 'Di 5-18'), ('Kehnaba', 'Kehnaba'), ('Oway', 'Oway')], default='', max_length=64, validators=[django.core.validators.RegexValidator('^(|M|F)$')]),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='PPiIQII',
            field=models.CharField(blank=True, choices=[('', '(Empty)'), ('Di 5 o subra', 'Di 5 o subra'), ('Di', 'Di'), ('Oway', 'Oway')], default='', max_length=64, validators=[django.core.validators.RegexValidator('^(|M|F)$')]),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='PPiIQIII',
            field=models.CharField(blank=True, choices=[('', '(Empty)'), ('Da galbek', 'Da galbek'), ('Oway', 'Oway'), ('Di', 'Di')], default='', max_length=64, validators=[django.core.validators.RegexValidator('^(|M|F)$')]),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='PPiIVQI',
            field=models.CharField(blank=True, choices=[('', '(Empty)'), ('Di 5-18', 'Di 5-18'), ('Kehnaba', 'Kehnaba'), ('Oway', 'Oway')], default='', max_length=64, validators=[django.core.validators.RegexValidator('^(|M|F)$')]),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='PPiIVQII',
            field=models.CharField(blank=True, choices=[('', '(Empty)'), ('Di 5 o subra', 'Di 5 o subra'), ('Di', 'Di'), ('Oway', 'Oway')], default='', max_length=64, validators=[django.core.validators.RegexValidator('^(|M|F)$')]),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='PPiIVQIII',
            field=models.CharField(blank=True, choices=[('', '(Empty)'), ('Da galbek', 'Da galbek'), ('Oway', 'Oway'), ('Di', 'Di')], default='', max_length=64, validators=[django.core.validators.RegexValidator('^(|M|F)$')]),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='PPiIXQI',
            field=models.CharField(blank=True, choices=[('', '(Empty)'), ('Di 5-18', 'Di 5-18'), ('Kehnaba', 'Kehnaba'), ('Oway', 'Oway')], default='', max_length=64, validators=[django.core.validators.RegexValidator('^(|M|F)$')]),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='PPiIXQII',
            field=models.CharField(blank=True, choices=[('', '(Empty)'), ('Di 5 o subra', 'Di 5 o subra'), ('Di', 'Di'), ('Oway', 'Oway')], default='', max_length=64, validators=[django.core.validators.RegexValidator('^(|M|F)$')]),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='PPiIXQIII',
            field=models.CharField(blank=True, choices=[('', '(Empty)'), ('Da galbek', 'Da galbek'), ('Oway', 'Oway'), ('Di', 'Di')], default='', max_length=64, validators=[django.core.validators.RegexValidator('^(|M|F)$')]),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='PPiVIIIQI',
            field=models.CharField(blank=True, choices=[('', '(Empty)'), ('Di 5-18', 'Di 5-18'), ('Kehnaba', 'Kehnaba'), ('Oway', 'Oway')], default='', max_length=64, validators=[django.core.validators.RegexValidator('^(|M|F)$')]),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='PPiVIIIQII',
            field=models.CharField(blank=True, choices=[('', '(Empty)'), ('Di 5 o subra', 'Di 5 o subra'), ('Di', 'Di'), ('Oway', 'Oway')], default='', max_length=64, validators=[django.core.validators.RegexValidator('^(|M|F)$')]),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='PPiVIIIQIII',
            field=models.CharField(blank=True, choices=[('', '(Empty)'), ('Da galbek', 'Da galbek'), ('Oway', 'Oway'), ('Di', 'Di')], default='', max_length=64, validators=[django.core.validators.RegexValidator('^(|M|F)$')]),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='PPiVIIQI',
            field=models.CharField(blank=True, choices=[('', '(Empty)'), ('Di 5-18', 'Di 5-18'), ('Kehnaba', 'Kehnaba'), ('Oway', 'Oway')], default='', max_length=64, validators=[django.core.validators.RegexValidator('^(|M|F)$')]),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='PPiVIIQII',
            field=models.CharField(blank=True, choices=[('', '(Empty)'), ('Di 5 o subra', 'Di 5 o subra'), ('Di', 'Di'), ('Oway', 'Oway')], default='', max_length=64, validators=[django.core.validators.RegexValidator('^(|M|F)$')]),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='PPiVIIQIII',
            field=models.CharField(blank=True, choices=[('', '(Empty)'), ('Da galbek', 'Da galbek'), ('Oway', 'Oway'), ('Di', 'Di')], default='', max_length=64, validators=[django.core.validators.RegexValidator('^(|M|F)$')]),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='PPiVIQI',
            field=models.CharField(blank=True, choices=[('', '(Empty)'), ('Di 5-18', 'Di 5-18'), ('Kehnaba', 'Kehnaba'), ('Oway', 'Oway')], default='', max_length=64, validators=[django.core.validators.RegexValidator('^(|M|F)$')]),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='PPiVIQII',
            field=models.CharField(blank=True, choices=[('', '(Empty)'), ('Di 5 o subra', 'Di 5 o subra'), ('Di', 'Di'), ('Oway', 'Oway')], default='', max_length=64, validators=[django.core.validators.RegexValidator('^(|M|F)$')]),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='PPiVIQIII',
            field=models.CharField(blank=True, choices=[('', '(Empty)'), ('Da galbek', 'Da galbek'), ('Oway', 'Oway'), ('Di', 'Di')], default='', max_length=64, validators=[django.core.validators.RegexValidator('^(|M|F)$')]),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='PPiVQI',
            field=models.CharField(blank=True, choices=[('', '(Empty)'), ('Di 5-18', 'Di 5-18'), ('Kehnaba', 'Kehnaba'), ('Oway', 'Oway')], default='', max_length=64, validators=[django.core.validators.RegexValidator('^(|M|F)$')]),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='PPiVQII',
            field=models.CharField(blank=True, choices=[('', '(Empty)'), ('Di 5 o subra', 'Di 5 o subra'), ('Di', 'Di'), ('Oway', 'Oway')], default='', max_length=64, validators=[django.core.validators.RegexValidator('^(|M|F)$')]),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='PPiVQIII',
            field=models.CharField(blank=True, choices=[('', '(Empty)'), ('Da galbek', 'Da galbek'), ('Oway', 'Oway'), ('Di', 'Di')], default='', max_length=64, validators=[django.core.validators.RegexValidator('^(|M|F)$')]),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='PPiXQI',
            field=models.CharField(blank=True, choices=[('', '(Empty)'), ('Di 5-18', 'Di 5-18'), ('Kehnaba', 'Kehnaba'), ('Oway', 'Oway')], default='', max_length=64, validators=[django.core.validators.RegexValidator('^(|M|F)$')]),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='PPiXQII',
            field=models.CharField(blank=True, choices=[('', '(Empty)'), ('Di 5 o subra', 'Di 5 o subra'), ('Di', 'Di'), ('Oway', 'Oway')], default='', max_length=64, validators=[django.core.validators.RegexValidator('^(|M|F)$')]),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='PPiXQIII',
            field=models.CharField(blank=True, choices=[('', '(Empty)'), ('Da galbek', 'Da galbek'), ('Oway', 'Oway'), ('Di', 'Di')], default='', max_length=64, validators=[django.core.validators.RegexValidator('^(|M|F)$')]),
        ),
    ]
