# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-22 10:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcari', '0077_auto_20180422_0137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respondent',
            old_name='curaddress',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='respondent',
            name='peraddress',
        ),
    ]
