# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-22 15:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcari', '0078_auto_20180422_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respondent',
            name='PPiIIIQIII',
            field=models.CharField(blank=True, choices=[('', '(Empty)'), ('Hindi nagtatrabaho', 'Hindi nagtatrabaho'), ('Magsasaka', 'Magsasaka'), ('Mangingisda', 'Mangingisda'), ('Magsasaka', 'Magsasaka'), ('Trabahador', 'Trabahador'), ('Uring Manggagawa', 'Uring Manggagawa'), ('Wala sa nabanggit', 'Wala sa nabanggit')], default='', max_length=64, validators=[django.core.validators.RegexValidator('^(|M|F)$')]),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='PPiIIQIII',
            field=models.CharField(blank=True, choices=[('', '(Empty)'), ('Hindi nagtatrabaho', 'Hindi nagtatrabaho'), ('Magsasaka', 'Magsasaka'), ('Mangingisda', 'Mangingisda'), ('Magsasaka', 'Magsasaka'), ('Trabahador', 'Trabahador'), ('Uring Manggagawa', 'Uring Manggagawa'), ('Wala sa nabanggit', 'Wala sa nabanggit')], default='', max_length=64, validators=[django.core.validators.RegexValidator('^(|M|F)$')]),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='PPiIQIII',
            field=models.CharField(blank=True, choices=[('', '(Empty)'), ('Hindi nagtatrabaho', 'Hindi nagtatrabaho'), ('Magsasaka', 'Magsasaka'), ('Mangingisda', 'Mangingisda'), ('Magsasaka', 'Magsasaka'), ('Trabahador', 'Trabahador'), ('Uring Manggagawa', 'Uring Manggagawa'), ('Wala sa nabanggit', 'Wala sa nabanggit')], default='', max_length=64, validators=[django.core.validators.RegexValidator('^(|M|F)$')]),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='PPiIVQIII',
            field=models.CharField(blank=True, choices=[('', '(Empty)'), ('Hindi nagtatrabaho', 'Hindi nagtatrabaho'), ('Magsasaka', 'Magsasaka'), ('Mangingisda', 'Mangingisda'), ('Magsasaka', 'Magsasaka'), ('Trabahador', 'Trabahador'), ('Uring Manggagawa', 'Uring Manggagawa'), ('Wala sa nabanggit', 'Wala sa nabanggit')], default='', max_length=64, validators=[django.core.validators.RegexValidator('^(|M|F)$')]),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='PPiIXQIII',
            field=models.CharField(blank=True, choices=[('', '(Empty)'), ('Hindi nagtatrabaho', 'Hindi nagtatrabaho'), ('Magsasaka', 'Magsasaka'), ('Mangingisda', 'Mangingisda'), ('Magsasaka', 'Magsasaka'), ('Trabahador', 'Trabahador'), ('Uring Manggagawa', 'Uring Manggagawa'), ('Wala sa nabanggit', 'Wala sa nabanggit')], default='', max_length=64, validators=[django.core.validators.RegexValidator('^(|M|F)$')]),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='PPiVIIIQIII',
            field=models.CharField(blank=True, choices=[('', '(Empty)'), ('Hindi nagtatrabaho', 'Hindi nagtatrabaho'), ('Magsasaka', 'Magsasaka'), ('Mangingisda', 'Mangingisda'), ('Magsasaka', 'Magsasaka'), ('Trabahador', 'Trabahador'), ('Uring Manggagawa', 'Uring Manggagawa'), ('Wala sa nabanggit', 'Wala sa nabanggit')], default='', max_length=64, validators=[django.core.validators.RegexValidator('^(|M|F)$')]),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='PPiVIIQIII',
            field=models.CharField(blank=True, choices=[('', '(Empty)'), ('Hindi nagtatrabaho', 'Hindi nagtatrabaho'), ('Magsasaka', 'Magsasaka'), ('Mangingisda', 'Mangingisda'), ('Magsasaka', 'Magsasaka'), ('Trabahador', 'Trabahador'), ('Uring Manggagawa', 'Uring Manggagawa'), ('Wala sa nabanggit', 'Wala sa nabanggit')], default='', max_length=64, validators=[django.core.validators.RegexValidator('^(|M|F)$')]),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='PPiVIQIII',
            field=models.CharField(blank=True, choices=[('', '(Empty)'), ('Hindi nagtatrabaho', 'Hindi nagtatrabaho'), ('Magsasaka', 'Magsasaka'), ('Mangingisda', 'Mangingisda'), ('Magsasaka', 'Magsasaka'), ('Trabahador', 'Trabahador'), ('Uring Manggagawa', 'Uring Manggagawa'), ('Wala sa nabanggit', 'Wala sa nabanggit')], default='', max_length=64, validators=[django.core.validators.RegexValidator('^(|M|F)$')]),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='PPiVQIII',
            field=models.CharField(blank=True, choices=[('', '(Empty)'), ('Hindi nagtatrabaho', 'Hindi nagtatrabaho'), ('Magsasaka', 'Magsasaka'), ('Mangingisda', 'Mangingisda'), ('Magsasaka', 'Magsasaka'), ('Trabahador', 'Trabahador'), ('Uring Manggagawa', 'Uring Manggagawa'), ('Wala sa nabanggit', 'Wala sa nabanggit')], default='', max_length=64, validators=[django.core.validators.RegexValidator('^(|M|F)$')]),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='PPiXQIII',
            field=models.CharField(blank=True, choices=[('', '(Empty)'), ('Hindi nagtatrabaho', 'Hindi nagtatrabaho'), ('Magsasaka', 'Magsasaka'), ('Mangingisda', 'Mangingisda'), ('Magsasaka', 'Magsasaka'), ('Trabahador', 'Trabahador'), ('Uring Manggagawa', 'Uring Manggagawa'), ('Wala sa nabanggit', 'Wala sa nabanggit')], default='', max_length=64, validators=[django.core.validators.RegexValidator('^(|M|F)$')]),
        ),
    ]
